export const USER_DATA = 'user_data';
export const REGISTERED_DATA = 'registerd_data';
export const COUNTRY_DATA = 'country_data';
export const COUNTRY_ID = 'country_id';
export const FLAG_ID = 'flag_id';
export const FLAG = 'flag';
export const SKIP= 'skip';
export const CLIENT_DATA = 'client_data';
export const FORM_STEP = 'form_step'
export const FIRST_STEP = 'first_step'
export const SECOND_STEP = 'second_step'
export const THIRD_STEP = 'third_step'