name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker-compose build

      - name: Tag Docker image
        run: docker tag frontend_communities ezekielkaeyros/eze_communities

      - name: Tag Docker image
        run: docker tag backend_communities ezekielkaeyros/backend_eze_communities

      - name: Tag Docker image
        run: docker tag landing_communities ezekielkaeyros/eze_landingpage

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ezekielkaeyros/eze_communities:latest

      - name: Push Docker image
        run: docker push ezekielkaeyros/backend_eze_communities:latest

      - name: Push Docker image
        run: docker push ezekielkaeyros/eze_landingpage:latest